# Generated by Django 4.0.6 on 2022-09-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=13, unique=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=13, unique=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='identificacion',
            field=models.IntegerField(unique=True, verbose_name='N° de documento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=13, unique=True, verbose_name='Teléfono'),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
    ]
