# Generated by Django 4.0.6 on 2022-09-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='fechaf',
            field=models.DateField(verbose_name='Fecha final'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='fechai',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
    ]
